[tool.poetry]
name = "woocommerce-helper"
version = "0.1.0"
description = ""
authors = ["Samyak Bardiya <mail@samyakbardiya.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
